// <auto-generated />
using System;
using GameStatistics.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameStatistics.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameStatistics.Models.GameData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AverageBetAmount")
                        .HasColumnType("real");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("PopularityScore")
                        .HasColumnType("real");

                    b.Property<int>("TotalBets")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GamesData", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f17ea857-18ef-498a-88f8-d2e2ff353890"),
                            AverageBetAmount = 10.5f,
                            Category = "Casinos",
                            GameName = "Poker",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2030),
                            PopularityScore = 8.2f,
                            TotalBets = 1000,
                            TotalWins = 500
                        },
                        new
                        {
                            Id = new Guid("1be607c4-e619-4afc-a8db-198652df190a"),
                            AverageBetAmount = 15.2f,
                            Category = "Casinos",
                            GameName = "Blackjack",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2060),
                            PopularityScore = 7.6f,
                            TotalBets = 1500,
                            TotalWins = 800
                        },
                        new
                        {
                            Id = new Guid("5ff8caee-165a-4beb-b4f0-d7d1de637c05"),
                            AverageBetAmount = 2.5f,
                            Category = "Recreational machines",
                            GameName = "Slot Machines",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2070),
                            PopularityScore = 9.3f,
                            TotalBets = 5000,
                            TotalWins = 2000
                        },
                        new
                        {
                            Id = new Guid("420f48a8-722e-47c6-a46e-f8bda03d9700"),
                            AverageBetAmount = 20f,
                            Category = "Casinos",
                            GameName = "Roulette",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2080),
                            PopularityScore = 6.9f,
                            TotalBets = 2000,
                            TotalWins = 1000
                        },
                        new
                        {
                            Id = new Guid("42d8ab88-491f-4b27-bc07-8acfafaa3889"),
                            AverageBetAmount = 12.8f,
                            Category = "Casinos",
                            GameName = "Craps",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2090),
                            PopularityScore = 5.4f,
                            TotalBets = 800,
                            TotalWins = 300
                        },
                        new
                        {
                            Id = new Guid("e0739932-2538-48c0-9cf3-99c264fb1a38"),
                            AverageBetAmount = 5.7f,
                            Category = "Recreational machines",
                            GameName = "Bingo",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2100),
                            PopularityScore = 7.8f,
                            TotalBets = 300,
                            TotalWins = 150
                        },
                        new
                        {
                            Id = new Guid("e1df340b-8c25-49d3-9495-c352f107165d"),
                            AverageBetAmount = 6.2f,
                            Category = "Recreational machines",
                            GameName = "Keno",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2110),
                            PopularityScore = 6.1f,
                            TotalBets = 400,
                            TotalWins = 200
                        },
                        new
                        {
                            Id = new Guid("8962a450-bd4c-455f-843f-ad5caf76079e"),
                            AverageBetAmount = 50f,
                            Category = "Sports",
                            GameName = "Sports Betting",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2120),
                            PopularityScore = 9.7f,
                            TotalBets = 5000,
                            TotalWins = 2500
                        },
                        new
                        {
                            Id = new Guid("4ed4d50f-9e3a-41bf-846d-b5928fdd9036"),
                            AverageBetAmount = 25f,
                            Category = "Sports",
                            GameName = "Horse Racing",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2130),
                            PopularityScore = 8.4f,
                            TotalBets = 3000,
                            TotalWins = 1200
                        },
                        new
                        {
                            Id = new Guid("abbb08a2-e1bf-4ec3-9d10-af1137dae58b"),
                            AverageBetAmount = 35f,
                            Category = "Sports",
                            GameName = "Soccer Betting",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2140),
                            PopularityScore = 7.2f,
                            TotalBets = 2000,
                            TotalWins = 900
                        },
                        new
                        {
                            Id = new Guid("6e0b6b67-9156-4c74-9455-2eda0be219be"),
                            AverageBetAmount = 42f,
                            Category = "Sports",
                            GameName = "Basketball Betting",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2150),
                            PopularityScore = 6.8f,
                            TotalBets = 1800,
                            TotalWins = 800
                        },
                        new
                        {
                            Id = new Guid("19e44f74-fa25-4284-90ea-e6f02be75613"),
                            AverageBetAmount = 48f,
                            Category = "Sports",
                            GameName = "Baseball Betting",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2160),
                            PopularityScore = 6.5f,
                            TotalBets = 1500,
                            TotalWins = 700
                        },
                        new
                        {
                            Id = new Guid("dbd0e0a3-06b5-4ac4-92b3-6b84d4a044b4"),
                            AverageBetAmount = 55f,
                            Category = "Sports",
                            GameName = "Cricket Betting",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2170),
                            PopularityScore = 6.2f,
                            TotalBets = 1200,
                            TotalWins = 600
                        },
                        new
                        {
                            Id = new Guid("7aac3357-d104-40ab-8971-862e257c8aca"),
                            AverageBetAmount = 60f,
                            Category = "Sports",
                            GameName = "Tennis Betting",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2180),
                            PopularityScore = 6f,
                            TotalBets = 1000,
                            TotalWins = 500
                        },
                        new
                        {
                            Id = new Guid("b1e4694f-167f-4ff2-94d1-50574cf2d2fc"),
                            AverageBetAmount = 70f,
                            Category = "Sports",
                            GameName = "Golf Betting",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2190),
                            PopularityScore = 5.7f,
                            TotalBets = 800,
                            TotalWins = 400
                        },
                        new
                        {
                            Id = new Guid("72c28d6f-4e1b-4ef7-952c-2b356d26e81d"),
                            AverageBetAmount = 80f,
                            Category = "Sports",
                            GameName = "Boxing Betting",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2200),
                            PopularityScore = 5.4f,
                            TotalBets = 600,
                            TotalWins = 300
                        },
                        new
                        {
                            Id = new Guid("190fdde3-8026-4e39-9536-0f1c71d9739c"),
                            AverageBetAmount = 100f,
                            Category = "Sports",
                            GameName = "MMA Betting",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2210),
                            PopularityScore = 5.1f,
                            TotalBets = 400,
                            TotalWins = 200
                        },
                        new
                        {
                            Id = new Guid("289a4fbb-bea1-47a4-9e9a-20c5a944ec0f"),
                            AverageBetAmount = 200f,
                            Category = "Sports",
                            GameName = "Cycling Betting",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2240),
                            PopularityScore = 4.8f,
                            TotalBets = 200,
                            TotalWins = 100
                        },
                        new
                        {
                            Id = new Guid("2b6a5c2f-f6eb-4907-ab9c-0dd42ece1f56"),
                            AverageBetAmount = 10f,
                            Category = "Recreational machines",
                            GameName = "Fishing Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2250),
                            PopularityScore = 7.5f,
                            TotalBets = 100,
                            TotalWins = 50
                        },
                        new
                        {
                            Id = new Guid("3423cdf8-2e47-421d-b1aa-03ebea2f5bec"),
                            AverageBetAmount = 5f,
                            Category = "Recreational machines",
                            GameName = "Bowling Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2260),
                            PopularityScore = 6.7f,
                            TotalBets = 50,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("85dc5646-47d3-4fbf-a997-0a2e4e0791f7"),
                            AverageBetAmount = 8f,
                            Category = "Recreational machines",
                            GameName = "Darts Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2270),
                            PopularityScore = 6f,
                            TotalBets = 80,
                            TotalWins = 30
                        },
                        new
                        {
                            Id = new Guid("b2556803-4c5e-451f-9ddd-df5414f772e0"),
                            AverageBetAmount = 12f,
                            Category = "Recreational machines",
                            GameName = "Guitar Hero Arcade",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2280),
                            PopularityScore = 8.7f,
                            TotalBets = 120,
                            TotalWins = 60
                        },
                        new
                        {
                            Id = new Guid("78d95543-5b4f-4afd-8bf0-053fcaa2f21c"),
                            AverageBetAmount = 9f,
                            Category = "Recreational machines",
                            GameName = "Air Hockey",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2290),
                            PopularityScore = 7.9f,
                            TotalBets = 90,
                            TotalWins = 40
                        },
                        new
                        {
                            Id = new Guid("91cbcdc6-6055-4794-96e9-c1f3b365eddc"),
                            AverageBetAmount = 7f,
                            Category = "Recreational machines",
                            GameName = "Foosball",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2300),
                            PopularityScore = 6.3f,
                            TotalBets = 70,
                            TotalWins = 25
                        },
                        new
                        {
                            Id = new Guid("66170f04-6a40-4d01-b2cc-5e95ece74845"),
                            AverageBetAmount = 6f,
                            Category = "Recreational machines",
                            GameName = "Skiing Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2310),
                            PopularityScore = 5.6f,
                            TotalBets = 60,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("e68d22df-e614-48f0-86d7-3d93449de452"),
                            AverageBetAmount = 10f,
                            Category = "Recreational machines",
                            GameName = "Basketball Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2320),
                            PopularityScore = 7.2f,
                            TotalBets = 100,
                            TotalWins = 40
                        },
                        new
                        {
                            Id = new Guid("6c04a998-9545-4a34-b844-7f14602d342a"),
                            AverageBetAmount = 15f,
                            Category = "Recreational machines",
                            GameName = "Football Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2330),
                            PopularityScore = 8.4f,
                            TotalBets = 150,
                            TotalWins = 60
                        },
                        new
                        {
                            Id = new Guid("fd651954-865d-4757-96ae-118b7f6c56f4"),
                            AverageBetAmount = 8f,
                            Category = "Recreational machines",
                            GameName = "Golf Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2340),
                            PopularityScore = 6.9f,
                            TotalBets = 80,
                            TotalWins = 30
                        },
                        new
                        {
                            Id = new Guid("9149fbc4-2f7c-4ad8-8759-29cca6253e8a"),
                            AverageBetAmount = 7f,
                            Category = "Recreational machines",
                            GameName = "Tennis Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2350),
                            PopularityScore = 6.1f,
                            TotalBets = 70,
                            TotalWins = 25
                        },
                        new
                        {
                            Id = new Guid("bb2fd604-cf76-457b-9f00-f0ab8c892781"),
                            AverageBetAmount = 5f,
                            Category = "Recreational machines",
                            GameName = "Volleyball Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2360),
                            PopularityScore = 5.3f,
                            TotalBets = 50,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("db2c1d0f-6c6e-46e1-b4bc-a56886de46ab"),
                            AverageBetAmount = 4f,
                            Category = "Recreational machines",
                            GameName = "Cricket Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2370),
                            PopularityScore = 4.6f,
                            TotalBets = 40,
                            TotalWins = 15
                        },
                        new
                        {
                            Id = new Guid("fa055017-4ce3-4486-9189-fe3784a62113"),
                            AverageBetAmount = 3f,
                            Category = "Recreational machines",
                            GameName = "Hockey Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2380),
                            PopularityScore = 3.9f,
                            TotalBets = 30,
                            TotalWins = 10
                        },
                        new
                        {
                            Id = new Guid("b69484ca-6276-4f77-8de2-ad7df0028f7d"),
                            AverageBetAmount = 9f,
                            Category = "Recreational machines",
                            GameName = "Racing Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2390),
                            PopularityScore = 7.5f,
                            TotalBets = 90,
                            TotalWins = 40
                        },
                        new
                        {
                            Id = new Guid("8c7aebb3-678a-4e71-b0fd-f9c2c312b077"),
                            AverageBetAmount = 6f,
                            Category = "Recreational machines",
                            GameName = "Boxing Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2400),
                            PopularityScore = 6.2f,
                            TotalBets = 60,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("f466ca9c-e6ce-4e63-8b93-78d77b05c135"),
                            AverageBetAmount = 4f,
                            Category = "Recreational machines",
                            GameName = "Wrestling Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2410),
                            PopularityScore = 5.1f,
                            TotalBets = 40,
                            TotalWins = 15
                        },
                        new
                        {
                            Id = new Guid("e3b5e3a1-1df8-4246-9980-7ec44ed17c37"),
                            AverageBetAmount = 8f,
                            Category = "Recreational machines",
                            GameName = "Soccer Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2420),
                            PopularityScore = 6.7f,
                            TotalBets = 80,
                            TotalWins = 30
                        },
                        new
                        {
                            Id = new Guid("3652c841-1505-4b27-98b6-df5fd0a8e92c"),
                            AverageBetAmount = 7f,
                            Category = "Recreational machines",
                            GameName = "Baseball Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2430),
                            PopularityScore = 6f,
                            TotalBets = 70,
                            TotalWins = 25
                        },
                        new
                        {
                            Id = new Guid("31a50744-3085-4df4-b013-bf9ff8072b03"),
                            AverageBetAmount = 5f,
                            Category = "Recreational machines",
                            GameName = "Basketball Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2440),
                            PopularityScore = 5.4f,
                            TotalBets = 50,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("2b5c87f9-31cc-4507-8417-f2ea369a7f81"),
                            AverageBetAmount = 3f,
                            Category = "Recreational machines",
                            GameName = "Volleyball Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2450),
                            PopularityScore = 4.8f,
                            TotalBets = 30,
                            TotalWins = 10
                        },
                        new
                        {
                            Id = new Guid("f49211bf-90a4-4f8b-9309-93487464f23d"),
                            AverageBetAmount = 4f,
                            Category = "Recreational machines",
                            GameName = "Tennis Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2460),
                            PopularityScore = 4.2f,
                            TotalBets = 40,
                            TotalWins = 15
                        },
                        new
                        {
                            Id = new Guid("fed34b58-1921-4194-9c2b-feb9da71c7ed"),
                            AverageBetAmount = 6f,
                            Category = "Recreational machines",
                            GameName = "Golf Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2470),
                            PopularityScore = 5.6f,
                            TotalBets = 60,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("f293c6aa-7e7b-4405-97a0-42797eb90a08"),
                            AverageBetAmount = 5f,
                            Category = "Recreational machines",
                            GameName = "Cricket Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2480),
                            PopularityScore = 5f,
                            TotalBets = 50,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("537ea549-4196-48a5-aa83-8a21e74bee2f"),
                            AverageBetAmount = 3f,
                            Category = "Recreational machines",
                            GameName = "Hockey Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2490),
                            PopularityScore = 4.4f,
                            TotalBets = 30,
                            TotalWins = 10
                        },
                        new
                        {
                            Id = new Guid("d9ed1646-a8b9-4dd8-8b61-3c2ec2fd2d38"),
                            AverageBetAmount = 4f,
                            Category = "Recreational machines",
                            GameName = "Racing Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2500),
                            PopularityScore = 4.9f,
                            TotalBets = 40,
                            TotalWins = 15
                        },
                        new
                        {
                            Id = new Guid("7b148f37-c325-4ca1-b859-341c532b3031"),
                            AverageBetAmount = 6f,
                            Category = "Recreational machines",
                            GameName = "Boxing Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2510),
                            PopularityScore = 5.5f,
                            TotalBets = 60,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("b40489cd-7944-4c22-986b-8c34c1cd7d87"),
                            AverageBetAmount = 7f,
                            Category = "Recreational machines",
                            GameName = "Wrestling Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2520),
                            PopularityScore = 6f,
                            TotalBets = 70,
                            TotalWins = 25
                        },
                        new
                        {
                            Id = new Guid("f425291f-5b74-4957-8d38-13f2973cb4cd"),
                            AverageBetAmount = 8f,
                            Category = "Recreational machines",
                            GameName = "Soccer Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2530),
                            PopularityScore = 6.5f,
                            TotalBets = 80,
                            TotalWins = 30
                        },
                        new
                        {
                            Id = new Guid("631c6e19-797d-4628-88b0-e4500d012595"),
                            AverageBetAmount = 9f,
                            Category = "Recreational machines",
                            GameName = "Baseball Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2540),
                            PopularityScore = 7f,
                            TotalBets = 90,
                            TotalWins = 40
                        },
                        new
                        {
                            Id = new Guid("aefb7691-2ab7-4031-bdf4-ffe66ae263dc"),
                            AverageBetAmount = 10f,
                            Category = "Recreational machines",
                            GameName = "Basketball Game",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2550),
                            PopularityScore = 7.5f,
                            TotalBets = 100,
                            TotalWins = 40
                        },
                        new
                        {
                            Id = new Guid("961c235d-d968-428c-8273-69fb0409b9e5"),
                            AverageBetAmount = 10.5f,
                            Category = "Card Game",
                            GameName = "Poker",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2560),
                            PopularityScore = 8.7f,
                            TotalBets = 10000,
                            TotalWins = 5000
                        },
                        new
                        {
                            Id = new Guid("d5e3952b-33a1-40a8-9e7b-9389eab9e2b4"),
                            AverageBetAmount = 15.2f,
                            Category = "Card Game",
                            GameName = "Blackjack",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2570),
                            PopularityScore = 9.2f,
                            TotalBets = 15000,
                            TotalWins = 7500
                        },
                        new
                        {
                            Id = new Guid("2f091a8d-ea9e-42ab-9198-cb1cba62fc46"),
                            AverageBetAmount = 25f,
                            Category = "Table Game",
                            GameName = "Roulette",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2580),
                            PopularityScore = 7.9f,
                            TotalBets = 20000,
                            TotalWins = 10000
                        },
                        new
                        {
                            Id = new Guid("3f5436ec-7229-41f1-99d0-42fe11c0aa49"),
                            AverageBetAmount = 5f,
                            Category = "Recreational Machine",
                            GameName = "Slot Machine",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2590),
                            PopularityScore = 9.8f,
                            TotalBets = 50000,
                            TotalWins = 25000
                        },
                        new
                        {
                            Id = new Guid("89c2fa39-dc68-4bf8-9fd5-3c3ed215bd16"),
                            AverageBetAmount = 20f,
                            Category = "Card Game",
                            GameName = "Baccarat",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2600),
                            PopularityScore = 6.5f,
                            TotalBets = 8000,
                            TotalWins = 4000
                        },
                        new
                        {
                            Id = new Guid("51f841b6-8683-43ca-85f5-3b5b783bc155"),
                            AverageBetAmount = 18.2f,
                            Category = "Table Game",
                            GameName = "Craps",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2610),
                            PopularityScore = 7.1f,
                            TotalBets = 12000,
                            TotalWins = 6000
                        },
                        new
                        {
                            Id = new Guid("ea9938ef-0cf1-4ad1-94e0-4c3c563b5de4"),
                            AverageBetAmount = 2.5f,
                            Category = "Recreational Game",
                            GameName = "Keno",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2620),
                            PopularityScore = 5.3f,
                            TotalBets = 3000,
                            TotalWins = 1500
                        },
                        new
                        {
                            Id = new Guid("0d6d2e64-b077-4dc6-ac9e-8eef432a6ed7"),
                            AverageBetAmount = 10f,
                            Category = "Dice Game",
                            GameName = "Sic Bo",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2630),
                            PopularityScore = 4.6f,
                            TotalBets = 6000,
                            TotalWins = 3000
                        },
                        new
                        {
                            Id = new Guid("8890e2f4-4cdf-4460-96ed-53a95e758675"),
                            AverageBetAmount = 12.5f,
                            Category = "Card Game",
                            GameName = "Pai Gow Poker",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2640),
                            PopularityScore = 6.9f,
                            TotalBets = 7000,
                            TotalWins = 3500
                        },
                        new
                        {
                            Id = new Guid("cd57a872-68c9-4dc9-b777-2e46fb359381"),
                            AverageBetAmount = 10f,
                            Category = "Recreational Machine",
                            GameName = "Wheel of Fortune",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2650),
                            PopularityScore = 8.2f,
                            TotalBets = 10000,
                            TotalWins = 5000
                        },
                        new
                        {
                            Id = new Guid("c76d8d57-9134-458d-8fb0-703c7df21c63"),
                            AverageBetAmount = 15.3f,
                            Category = "Card Game",
                            GameName = "Texas Hold'em",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2650),
                            PopularityScore = 9.5f,
                            TotalBets = 18000,
                            TotalWins = 9000
                        },
                        new
                        {
                            Id = new Guid("e72ecc29-d4c1-44dd-8125-d32b5d4769d2"),
                            AverageBetAmount = 10f,
                            Category = "Card Game",
                            GameName = "Three Card Poker",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2660),
                            PopularityScore = 8.4f,
                            TotalBets = 10000,
                            TotalWins = 5000
                        },
                        new
                        {
                            Id = new Guid("27896d44-dbca-48bd-9b14-50ac09e5b0a4"),
                            AverageBetAmount = 5f,
                            Category = "Recreational Game",
                            GameName = "Bingo",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2670),
                            PopularityScore = 7.6f,
                            TotalBets = 4000,
                            TotalWins = 2000
                        },
                        new
                        {
                            Id = new Guid("f2055f68-3d08-4e76-8ee3-1ee847ea835a"),
                            AverageBetAmount = 8f,
                            Category = "Card Game",
                            GameName = "Red Dog",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2680),
                            PopularityScore = 5.9f,
                            TotalBets = 3000,
                            TotalWins = 1500
                        },
                        new
                        {
                            Id = new Guid("67736f58-4e2f-486b-bfbe-af85c628387f"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Pachinko",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2690),
                            PopularityScore = 9f,
                            TotalBets = 20000,
                            TotalWins = 10000
                        },
                        new
                        {
                            Id = new Guid("aab6bd62-edb9-49e6-bd27-279f7305a9ee"),
                            AverageBetAmount = 10f,
                            Category = "Card Game",
                            GameName = "Crazy 4 Poker",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2700),
                            PopularityScore = 7.8f,
                            TotalBets = 5000,
                            TotalWins = 2500
                        },
                        new
                        {
                            Id = new Guid("fb5e9cd4-8640-47d1-8cd1-377b1bb6a3b2"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "War",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2710),
                            PopularityScore = 6.3f,
                            TotalBets = 4000,
                            TotalWins = 2000
                        },
                        new
                        {
                            Id = new Guid("eb0bf288-f432-46d6-b519-b4df60b87eec"),
                            AverageBetAmount = 5f,
                            Category = "Recreational Machine",
                            GameName = "Big Six Wheel",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2720),
                            PopularityScore = 8.1f,
                            TotalBets = 8000,
                            TotalWins = 4000
                        },
                        new
                        {
                            Id = new Guid("1cfffeb9-66a3-4ab2-b1b3-208610be7a73"),
                            AverageBetAmount = 12f,
                            Category = "Card Game",
                            GameName = "Caribbean Stud Poker",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2750),
                            PopularityScore = 7.4f,
                            TotalBets = 9000,
                            TotalWins = 4500
                        },
                        new
                        {
                            Id = new Guid("1ba7f88e-e0db-4f30-a4b8-0956d58c1806"),
                            AverageBetAmount = 0.5f,
                            Category = "Recreational Machine",
                            GameName = "Penny Slots",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2760),
                            PopularityScore = 9.6f,
                            TotalBets = 25000,
                            TotalWins = 12500
                        },
                        new
                        {
                            Id = new Guid("a8c34bfb-a17a-4b15-9426-1e4db5565872"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Cribbage",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2770),
                            PopularityScore = 4.9f,
                            TotalBets = 2000,
                            TotalWins = 1000
                        },
                        new
                        {
                            Id = new Guid("781a73c3-0275-43c0-847e-ab9510ccd4b9"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Video Poker",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2780),
                            PopularityScore = 9.3f,
                            TotalBets = 15000,
                            TotalWins = 7500
                        },
                        new
                        {
                            Id = new Guid("71f7e935-42fb-493d-ae59-798f5f60a70c"),
                            AverageBetAmount = 10f,
                            Category = "Card Game",
                            GameName = "Pontoon",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2790),
                            PopularityScore = 6.7f,
                            TotalBets = 6000,
                            TotalWins = 3000
                        },
                        new
                        {
                            Id = new Guid("989783e6-2134-4200-9c28-4e2e6f17a4b4"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Fruit Machine",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2800),
                            PopularityScore = 8.5f,
                            TotalBets = 10000,
                            TotalWins = 5000
                        },
                        new
                        {
                            Id = new Guid("d0292045-b463-4ff9-90fe-09ea16cf19a6"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Gin Rummy",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2810),
                            PopularityScore = 5.2f,
                            TotalBets = 3000,
                            TotalWins = 1500
                        },
                        new
                        {
                            Id = new Guid("a62d8d80-4b7b-4137-bbdb-771ccf29f699"),
                            AverageBetAmount = 2f,
                            Category = "Recreational Machine",
                            GameName = "Video Slots",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2820),
                            PopularityScore = 9.7f,
                            TotalBets = 35000,
                            TotalWins = 17500
                        },
                        new
                        {
                            Id = new Guid("d2bc84f7-cc56-47db-9cb5-1b3735b4e7a3"),
                            AverageBetAmount = 5f,
                            Category = "Board Game",
                            GameName = "Backgammon",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2830),
                            PopularityScore = 7.3f,
                            TotalBets = 5000,
                            TotalWins = 2500
                        },
                        new
                        {
                            Id = new Guid("1b617f9e-90d9-41be-983c-929d7207a8e6"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Keno Slot",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2830),
                            PopularityScore = 8.9f,
                            TotalBets = 12000,
                            TotalWins = 6000
                        },
                        new
                        {
                            Id = new Guid("94c9c5fb-8a48-42a8-aeb2-687fa7454c1a"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Hearts",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2840),
                            PopularityScore = 6.1f,
                            TotalBets = 4000,
                            TotalWins = 2000
                        },
                        new
                        {
                            Id = new Guid("427d22e9-4058-4fb2-9b7b-cc4798816045"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Video Keno",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2850),
                            PopularityScore = 9.1f,
                            TotalBets = 18000,
                            TotalWins = 9000
                        },
                        new
                        {
                            Id = new Guid("a25d25fb-3a56-4086-b035-2ec1f63e2461"),
                            AverageBetAmount = 10f,
                            Category = "Card Game",
                            GameName = "Cassino",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2860),
                            PopularityScore = 6.4f,
                            TotalBets = 7000,
                            TotalWins = 3500
                        },
                        new
                        {
                            Id = new Guid("9928415b-13b0-4235-8416-6bc95fc89c4c"),
                            AverageBetAmount = 2f,
                            Category = "Recreational Machine",
                            GameName = "Slingo",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2870),
                            PopularityScore = 8.3f,
                            TotalBets = 10000,
                            TotalWins = 5000
                        },
                        new
                        {
                            Id = new Guid("12413d34-2903-4e55-b28c-7a0154f0cf88"),
                            AverageBetAmount = 8f,
                            Category = "Card Game",
                            GameName = "Gin Poker",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2880),
                            PopularityScore = 5.7f,
                            TotalBets = 5000,
                            TotalWins = 2500
                        },
                        new
                        {
                            Id = new Guid("c5a4b6c3-9509-42ed-a2fc-f8661abc49c4"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Video Lottery Terminal",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2890),
                            PopularityScore = 9.4f,
                            TotalBets = 30000,
                            TotalWins = 15000
                        },
                        new
                        {
                            Id = new Guid("17cdfc57-d5d3-43ed-a375-e9154c58a82d"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Canasta",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2900),
                            PopularityScore = 4.8f,
                            TotalBets = 2000,
                            TotalWins = 1000
                        },
                        new
                        {
                            Id = new Guid("c710b0c4-c964-4ecf-8342-f4db099bb306"),
                            AverageBetAmount = 0.5f,
                            Category = "Recreational Machine",
                            GameName = "Penny Arcade Slots",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2910),
                            PopularityScore = 9.9f,
                            TotalBets = 35000,
                            TotalWins = 17500
                        },
                        new
                        {
                            Id = new Guid("02ee6536-551c-4753-b197-7e866f183030"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Crazy Eights",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2920),
                            PopularityScore = 5.4f,
                            TotalBets = 3000,
                            TotalWins = 1500
                        },
                        new
                        {
                            Id = new Guid("2f8be642-8ad6-45b9-968a-d93176128700"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Video Lottery",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2930),
                            PopularityScore = 9.7f,
                            TotalBets = 40000,
                            TotalWins = 20000
                        },
                        new
                        {
                            Id = new Guid("57ac02fb-6795-45f3-b811-7c95352e243f"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Pinochle",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2940),
                            PopularityScore = 5.1f,
                            TotalBets = 2500,
                            TotalWins = 1250
                        },
                        new
                        {
                            Id = new Guid("d1cb46a0-1d81-44d8-b771-2e0974f0c22e"),
                            AverageBetAmount = 0.5f,
                            Category = "Recreational Machine",
                            GameName = "Penny Roulette",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2950),
                            PopularityScore = 8.6f,
                            TotalBets = 10000,
                            TotalWins = 5000
                        },
                        new
                        {
                            Id = new Guid("90975eac-408c-4691-9b1f-ff807282faf4"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Euchre",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2960),
                            PopularityScore = 4.7f,
                            TotalBets = 3000,
                            TotalWins = 1500
                        },
                        new
                        {
                            Id = new Guid("a4ed4738-c008-4ec3-a816-72fce9f287c0"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Video Blackjack",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2970),
                            PopularityScore = 9.5f,
                            TotalBets = 20000,
                            TotalWins = 10000
                        },
                        new
                        {
                            Id = new Guid("d77e8cf9-7b6c-4921-9485-1be14915d970"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Spades",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2980),
                            PopularityScore = 6.2f,
                            TotalBets = 4000,
                            TotalWins = 2000
                        },
                        new
                        {
                            Id = new Guid("67bc6071-e7fe-45fa-a964-66954594341c"),
                            AverageBetAmount = 0.5f,
                            Category = "Recreational Machine",
                            GameName = "Penny Poker",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(2990),
                            PopularityScore = 9.2f,
                            TotalBets = 15000,
                            TotalWins = 7500
                        },
                        new
                        {
                            Id = new Guid("7a15fc1f-4b3b-423b-ad90-29dcfd2bc4b4"),
                            AverageBetAmount = 8f,
                            Category = "Card Game",
                            GameName = "Cribbage Poker",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(3000),
                            PopularityScore = 6.6f,
                            TotalBets = 5000,
                            TotalWins = 2500
                        },
                        new
                        {
                            Id = new Guid("8431c3b4-ed06-4aca-9f12-62c099f83f28"),
                            AverageBetAmount = 0.5f,
                            Category = "Recreational Machine",
                            GameName = "Penny Bingo",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(3010),
                            PopularityScore = 8f,
                            TotalBets = 10000,
                            TotalWins = 5000
                        },
                        new
                        {
                            Id = new Guid("53aa27cc-337e-4c29-a8ed-2256e152c641"),
                            AverageBetAmount = 8f,
                            Category = "Card Game",
                            GameName = "Gin Rummy Poker",
                            LastUpdated = new DateTime(2023, 11, 13, 0, 41, 40, 457, DateTimeKind.Utc).AddTicks(3020),
                            PopularityScore = 5.6f,
                            TotalBets = 3000,
                            TotalWins = 1500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
